CREATE TABLE IF NOT EXISTS REMISE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    montant_min DOUBLE NOT NULL,
    montant_max DOUBLE NOT NULL,
    taux DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS "TRANSACTION" (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    date TIMESTAMP NOT NULL,
    montant_avant DOUBLE NOT NULL,
    montant_apres DOUBLE NOT NULL,
    remise_id BIGINT,
    CONSTRAINT fk_transaction_remise FOREIGN KEY (remise_id) REFERENCES REMISE(id)
);